package com.zjcjava.entities.devicegps;

public class DeviceGps {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devicegps.ID
     *
     * @mbggenerated Wed Oct 21 16:44:39 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devicegps.device_id
     *
     * @mbggenerated Wed Oct 21 16:44:39 CST 2015
     */
    private Integer device_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devicegps.lng
     *
     * @mbggenerated Wed Oct 21 16:44:39 CST 2015
     */
    private String lng;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devicegps.lat
     *
     * @mbggenerated Wed Oct 21 16:44:39 CST 2015
     */
    private String lat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devicegps.mark
     *
     * @mbggenerated Wed Oct 21 16:44:39 CST 2015
     */
    private String mark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devicegps.ID
     *
     * @return the value of devicegps.ID
     *
     * @mbggenerated Wed Oct 21 16:44:39 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column devicegps.ID
     *
     * @param id the value for devicegps.ID
     *
     * @mbggenerated Wed Oct 21 16:44:39 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devicegps.device_id
     *
     * @return the value of devicegps.device_id
     *
     * @mbggenerated Wed Oct 21 16:44:39 CST 2015
     */
    public Integer getDevice_id() {
        return device_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column devicegps.device_id
     *
     * @param device_id the value for devicegps.device_id
     *
     * @mbggenerated Wed Oct 21 16:44:39 CST 2015
     */
    public void setDevice_id(Integer device_id) {
        this.device_id = device_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devicegps.lng
     *
     * @return the value of devicegps.lng
     *
     * @mbggenerated Wed Oct 21 16:44:39 CST 2015
     */
    public String getLng() {
        return lng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column devicegps.lng
     *
     * @param lng the value for devicegps.lng
     *
     * @mbggenerated Wed Oct 21 16:44:39 CST 2015
     */
    public void setLng(String lng) {
        this.lng = lng == null ? null : lng.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devicegps.lat
     *
     * @return the value of devicegps.lat
     *
     * @mbggenerated Wed Oct 21 16:44:39 CST 2015
     */
    public String getLat() {
        return lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column devicegps.lat
     *
     * @param lat the value for devicegps.lat
     *
     * @mbggenerated Wed Oct 21 16:44:39 CST 2015
     */
    public void setLat(String lat) {
        this.lat = lat == null ? null : lat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devicegps.mark
     *
     * @return the value of devicegps.mark
     *
     * @mbggenerated Wed Oct 21 16:44:39 CST 2015
     */
    public String getMark() {
        return mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column devicegps.mark
     *
     * @param mark the value for devicegps.mark
     *
     * @mbggenerated Wed Oct 21 16:44:39 CST 2015
     */
    public void setMark(String mark) {
        this.mark = mark == null ? null : mark.trim();
    }
}